version: '{build}'
build_script:
- ps: >-
    $env:BUILD_VERSION=$env:APPVEYOR_BUILD_VERSION

    $env:RELEASE_TAG=$env:APPVEYOR_REPO_TAG_NAME

    .\build.ps1 Package
test_script:
- ps: >-
    .\build.ps1 UnitTest

    $build_success = $?


    # upload results to AppVeyor

    $wc = New-Object 'System.Net.WebClient'

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\Test.xml))


    if (-not $build_success) {
      exit 1
    }
artifacts:
- path: Output\Packages\*.nupkg
  name: Chocolatey Package
deploy:
- provider: NuGet
  server: https://chocolatey.org/
  api_key:
    secure: +zfBtvqI0yIQodWvYBH7F0q8Mgjvlk4jswvEowSayB9LR4KaD36mkoEJHvRbY1TX
  skip_symbols: true
  on:
    appveyor_repo_tag: true
- provider: NuGet
  api_key:
    secure: Vlw7m7mXEZ9XqlZBsQ4fzqDKjO8yTdtXhO9c04RnrD4zwhf6dx+lxBmC9TJ7EF6G
  skip_symbols: true
  on:
    appveyor_repo_tag: true
